---
resources:
- deployment.yaml
- service.yaml
patchesStrategicMerge:
- cluster-ip.yaml
patchesJson6902:
- path: tolerations.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: coredns
    namespace: kube-system
#EOF
