- op: add
  path: "/spec/template/spec/tolerations/-"
  value:
    operator: "Exists"
    effect: NoSchedule
- op: add
  path: "/spec/template/spec/tolerations/-"
  value:
    operator: "Exists"
    effect: NoExecute
#EOF
